baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ismael's website"
theme = "hello-friend-ng"

homeSubtitle = "Possible a personal portfolio website"
defaultTheme = "dark"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"


  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
